FROM apache/airflow:2.9.3-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
        python3-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir \
    boto3==1.35.0 \
    requests==2.32.3 \
    pyarrow==17.0.0 \
    apache-airflow-providers-apache-spark==4.10.1
